title: or1on
description: a passionate hobby CTF player from Switzerland 
encoding: UTF-8
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker

# needed for jekyll-sitemap generator
url: "https://or1on-ctf.github.io" 

# logo
avatar: /assets/images/hacker.jpg 

excerpt_separator: <!--more-->

plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - vendor

